[package]
name = "plugin-ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.47.0"

[package.metadata.component]
package = "pato:plugin-ui"

[package.metadata.component.dependencies]